version: "3.9"

services:
  laravelapp:
    container_name: laravel-11
    build: .
    restart: always
    ports:
      - "8003:80"
    env_file:
      - .env
    networks:
      - laravel

networks:
  laravel:
